const ADD_TO_CART = "ADD_TO_CART"
const UPDATE_QUANTITY = "UPDATE_QUANTITY"
const REMOVE_FROM_CART = "REMOVE_FROM_CART"
const LOAD_FROM_LOCAL_STORAGE = "LOAD_FROM_LOCAL_STORAGE"


export {
    ADD_TO_CART,
    UPDATE_QUANTITY,
    REMOVE_FROM_CART,
    LOAD_FROM_LOCAL_STORAGE
}