const LOAD_PRODUCTS = "LOAD_PRODUCTS"
const LOAD_PRODUCTS_SUCCESSFUL = "LOAD_PRODUCTS_SUCCESSFUL"
const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED"

export {
    LOAD_PRODUCTS,
    LOAD_PRODUCTS_SUCCESSFUL,
    LOAD_PRODUCTS_FAILED
}