const LOAD_PRODUCT = "LOAD_PRODUCT"
const LOAD_PRODUCT_SUCCESSFUL = "LOAD_PRODUCT_SUCCESSFUL"
const LOAD_PRODUCT_FAILED = "LOAD_PRODUCT_FAILED"

export {
    LOAD_PRODUCT,
    LOAD_PRODUCT_SUCCESSFUL,
    LOAD_PRODUCT_FAILED
}